apiVersion: v1
kind: Pod
metadata:
  name: private-reg
spec:
  containers:
  - name: private-reg-container
    image: 556658104288.dkr.ecr.us-east-1.amazonaws.com/arclab:latest
  imagePullSecrets:
  - name: regcred
